export const SET_GAME_STATE = "SET_GAME_STATE";
export const SET_NAME = "SET_NAME";
export const SET_COLOR = "SET_COLOR";
export const SET_STATE_FROM_SERVER = "SET_STATE_FROM_SERVER";

export const SET_NUMBER_SELECT_MODAL_TARGET = 'SET_NUMBER_SELECT_MODAL_TARGET';